# Generated by Django 3.2.6 on 2021-08-14 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BienRaiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('price', models.CharField(max_length=20)),
                ('common_expenses', models.IntegerField(blank=True, null=True)),
                ('m2_construction', models.IntegerField()),
                ('m2_terrain', models.IntegerField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('n_bath', models.IntegerField()),
                ('n_room', models.IntegerField()),
                ('n_parking', models.IntegerField()),
                ('n_flat', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('is_vent', models.BooleanField()),
                ('favorite', models.BooleanField()),
                ('region', models.IntegerField(choices=[(1, 'Bio-Bio'), (2, 'Metropolitana')], default=1)),
                ('operation', models.IntegerField(choices=[(1, 'Casas'), (2, 'Departamentos')], default=1)),
                ('type_p', models.IntegerField(choices=[(1, 'Venta'), (2, 'Arriendo')], default=1)),
                ('img_principal', models.ImageField(blank=True, null=True, upload_to=service.models.upload_location2)),
                ('code', models.IntegerField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='galeryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=service.models.upload_location)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.bienraiz')),
            ],
        ),
    ]
